name: flutter_game_framework_core
description: "The core part (dart-only) of the flutter_game_framework."
version: 0.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  analyzer: any
  build: any
  code_builder: any
  collection: ^1.18.0
  dart_style: any
  easy_localization: ^3.0.3
  expandable: any
  firebase_auth: ^4.15.0
  json_annotation: ^4.9.0
  meta: ^1.11.0
  pub_semver: ^2.1.5
  riverpod: 
  riverpod_annotation: 
  shared_preferences: any
  source_gen: any
  yust: ^3.21.1

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics_presets: ^2.14.0
  json_serializable: ^6.5.4
  lints: ^3.0.0
  matcher: ^0.12.15

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

