name: flutter_game_framework_ui
description: "The UI framework for the flutter_game_framework_core."
version: 0.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: any
  build: any
  code_builder: any
  collection: ^1.18.0
  dart_style: any
  easy_localization: ^3.0.3
  expandable: any
  firebase_auth: ^4.15.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: any
  go_router: any
  google_fonts: ^6.1.0
  json_annotation: ^4.9.0
  meta: ^1.11.0
  riverpod: 
  riverpod_annotation: 
  shared_preferences: any
  source_gen: any
  yust: ^3.21.1
  yust_ui: ^3.21.0
  flutter_game_framework_core:
    path: ../flutter_game_framework_core

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics_presets: ^2.14.0
  json_serializable: ^6.5.4
  lints: ^3.0.0
  matcher: ^0.12.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
        - family: CustomIcons
          fonts:
              - asset: assets/fonts/CustomIcons.ttf
        - family: Roboto
          fonts:
            - asset: assets/fonts/Roboto/Roboto-Regular.ttf
            - asset: assets/fonts/Roboto/Roboto-Bold.ttf
              weight: 700
